printWidth: 100
useTabs: true
tabWidth: 4
semi: true
singleQuote: true
trailingComma: 'none'
bracketSpacing: true
arrowParens: 'always'
overrides:
  - files:
      - 'package.json'
      - '*.yml'
      - '*.yaml'
      - '*.md'
      - '.*'
    options:
      tabWidth: 2
      trailingComma: 'all'
